### ISSUE TITLE
Needs more kek

### ISSUE THREAD

**Issue by twitchyliquid64** [liamzebedee/metric#28]
Kek is lacking on most UI elements

**Comment by twitchyliquid64** [comment]
Can we escalate this please

**Comment by liamzebedee** [comment]
Sorry, I've been soooooo busy with telling this guy at work how to ask someone out. It's been taking so long, maybe you wanna take this one into your own hands?

**Comment by twitchyliquid64** [comment]
@jableader do you want to weigh in on this issue? I think we need more hands on deck

**Comment by jableader** [comment]
i do agree that the kek factor could do with an increase of efforts

**Comment by jableader** [comment]
Kek level aside, I'm impressed

**Comment by liamzebedee** [comment]
Hmm, I think I'll need a more detailed model of these kek levels before I can rule any answer conclusive. That and this work guy still hasn't asked the girl out. I hope he does today so I can get back to this... Thanks though.
