### ISSUE TITLE
provide some working demo page

### ISSUE THREAD

**Issue by achtan** [liamzebedee/metric#29]
hi, provide some working demo page please

**Comment by liamzebedee** [comment]
Sorry, it's not that sort of app. Needs to be locally hosted, demo page would involve a shared public server which just leads to chaos.

Instructions provided in the README.

**Comment by achtan** [comment]
i have read the README and wiki, but i still dont know how to write `computed functions` for metrics

**Comment by achtan** [comment]
so at least add some initial seed data to application or so
